apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: frontend
  name: kserve-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      component: predictor
      serving.kserve.io/inferenceservice: test
  endpoints:
  - port: metrics
    interval: 5s
    path: /metrics